// <auto-generated />
using System;
using System.Collections.Generic;
using GeniView.Cloud.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeniView.Cloud.Migrations.Data
{
    [DbContext(typeof(GeniViewCloudDataRepository))]
    [Migration("20260226150545_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeniView.Cloud.Models.ApplicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Callsite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Https")
                        .HasColumnType("bit");

                    b.Property<string>("InnerException")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Logged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logger")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("GeniView.Cloud.Models.ApplicationUpdate", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownloadAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("LatestVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.ToTable("ApplicationUpdates");
                });

            modelBuilder.Entity("GeniView.Cloud.Models.DeviceEventNotification", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SendNotifications")
                        .HasColumnType("bit");

                    b.Property<Guid>("UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("DeviceEventActionNotifications");
                });

            modelBuilder.Entity("GeniView.Cloud.Models.MailServer", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("bit");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("ReplyTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MailServer");
                });

            modelBuilder.Entity("GeniView.Cloud.Models.UserActivityHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AffectedObject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserActivityHistory");
                });

            modelBuilder.Entity("GeniView.Data.Agent.Agent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AgentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentID")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AgentID")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.AgentBatteryLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("Agent_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("Battery_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("Bay")
                        .HasColumnType("int");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InternalBatteryLogCount")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("OperatingData", "GeniView.Data.Hardware.AgentBatteryLog.OperatingData#BatteryOperatingData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("AverageCurrent")
                                .HasColumnType("float");

                            b1.Property<double>("Current")
                                .HasColumnType("float");

                            b1.Property<int>("CycleCount")
                                .HasColumnType("int");

                            b1.Property<double>("Voltage")
                                .HasColumnType("float");

                            b1.ComplexProperty<Dictionary<string, object>>("BatteryOperatingStatus", "GeniView.Data.Hardware.AgentBatteryLog.OperatingData#BatteryOperatingData.BatteryOperatingStatus#BatteryOperatingStatus", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("StatusA")
                                        .HasColumnType("int");

                                    b2.Property<int?>("StatusARaw")
                                        .HasColumnType("int");

                                    b2.Property<string>("StatusAText")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("StatusB")
                                        .HasColumnType("int");

                                    b2.Property<int?>("StatusBRaw")
                                        .HasColumnType("int");

                                    b2.Property<string>("StatusBText")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SlowChangingDataA", "GeniView.Data.Hardware.AgentBatteryLog.SlowChangingDataA#BatterySlowChangingDataA", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AbsoluteStateOfCharge")
                                .HasColumnType("int");

                            b1.Property<double>("CalculatedCapacity")
                                .HasColumnType("float");

                            b1.Property<double>("DischargeCapacity")
                                .HasColumnType("float");

                            b1.Property<int>("EndOfLifeCapacity")
                                .HasColumnType("int");

                            b1.Property<int>("RelativeStateOfCharge")
                                .HasColumnType("int");

                            b1.Property<double>("RemainingCapacity")
                                .HasColumnType("float");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SlowChangingDataB", "GeniView.Data.Hardware.AgentBatteryLog.SlowChangingDataB#BatterySlowChangingDataB", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AvailableEnergy")
                                .HasColumnType("int");

                            b1.Property<int>("AvailablePower")
                                .HasColumnType("int");

                            b1.Property<int>("AverageTimeToEmpty")
                                .HasColumnType("int");

                            b1.Property<int>("AverageTimeToFull")
                                .HasColumnType("int");

                            b1.Property<int>("BatteryInternalTemperature")
                                .HasColumnType("int");

                            b1.Property<int>("DisplayBoardTemperature")
                                .HasColumnType("int");

                            b1.Property<int>("LifeTime")
                                .HasColumnType("int");

                            b1.Property<double>("PassedCharge")
                                .HasColumnType("float");

                            b1.ComplexProperty<Dictionary<string, object>>("DisplayBoardStatus", "GeniView.Data.Hardware.AgentBatteryLog.SlowChangingDataB#BatterySlowChangingDataB.DisplayBoardStatus#BatteryDisplayBoardStatus", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("ActiveLEDs")
                                        .HasColumnType("int");

                                    b2.Property<int?>("ChargeMode")
                                        .HasColumnType("int");

                                    b2.Property<bool?>("IsDisplayFlashing")
                                        .HasColumnType("bit");

                                    b2.Property<bool?>("IsDisplayRed")
                                        .HasColumnType("bit");

                                    b2.Property<int>("PerceivedStateOfCharge")
                                        .HasColumnType("int");

                                    b2.Property<int>("StatusRaw")
                                        .HasColumnType("int");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TimeEstimate", "GeniView.Data.Hardware.AgentBatteryLog.TimeEstimate#BatteryTimeEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Estimate")
                                .HasColumnType("float");

                            b1.Property<string>("EstimateDescription")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("EstimateMode")
                                .HasColumnType("int");
                        });

                    b.HasKey("ID");

                    b.HasIndex("Agent_ID");

                    b.HasIndex(new[] { "Battery_ID", "Timestamp" }, "IX_BatteryID_Timestamp");

                    b.ToTable("AgentBatteryLog");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.AgentDeviceLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("Agent_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("BatteriesCharging")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesChargingCount")
                        .HasColumnType("int");

                    b.Property<string>("BatteriesChargingText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteriesPoweringSystem")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesPoweringSystemCount")
                        .HasColumnType("int");

                    b.Property<string>("BatteriesPoweringSystemText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteriesPresent")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesPresentCount")
                        .HasColumnType("int");

                    b.Property<string>("BatteriesPresentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceCapacity")
                        .HasColumnType("int");

                    b.Property<long?>("Device_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("InternalDeviceLogCount")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsExternalPowerInputApplied")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsExternalPowerInputNotGood")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("Location", "GeniView.Data.Hardware.AgentDeviceLog.Location#DeviceLocation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsUnknown")
                                .HasColumnType("bit");

                            b1.Property<double>("Lattitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PowerInput", "GeniView.Data.Hardware.AgentDeviceLog.PowerInput#DevicePower", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Current")
                                .HasColumnType("float");

                            b1.Property<double>("Voltage")
                                .HasColumnType("float");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PowerOutput", "GeniView.Data.Hardware.AgentDeviceLog.PowerOutput#DevicePower", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Current")
                                .HasColumnType("float");

                            b1.Property<double>("Voltage")
                                .HasColumnType("float");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "GeniView.Data.Hardware.AgentDeviceLog.Status#DeviceStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<int?>("StatusRaw")
                                .HasColumnType("int");

                            b1.Property<string>("StatusText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Temperature")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TimeEstimate", "GeniView.Data.Hardware.AgentDeviceLog.TimeEstimate#DeviceTimeEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Estimate")
                                .HasColumnType("float");

                            b1.Property<string>("EstimateDescription")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("EstimateMode")
                                .HasColumnType("int");
                        });

                    b.HasKey("ID");

                    b.HasIndex("Agent_ID");

                    b.HasIndex(new[] { "Device_ID", "Timestamp" }, "IX_Device_ID_Timestamp");

                    b.ToTable("AgentDeviceLog");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.Battery", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("BatteryChemistry")
                        .HasColumnType("int");

                    b.Property<int>("BatteryConfiguration")
                        .HasColumnType("int");

                    b.Property<int>("BatteryPackFirmwareVersion")
                        .HasColumnType("int");

                    b.Property<string>("BatteryTechnology")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CommunityID")
                        .HasColumnType("bigint");

                    b.Property<double>("DesignCapacity")
                        .HasColumnType("float");

                    b.Property<double>("DesignVoltage")
                        .HasColumnType("float");

                    b.Property<int>("FirmwareVersion")
                        .HasColumnType("int");

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SerialNumberCode")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CommunityID");

                    b.HasIndex("GroupID");

                    b.HasIndex("SerialNumberCode")
                        .IsUnique()
                        .HasFilter("[SerialNumberCode] IS NOT NULL");

                    b.ToTable("Batteries");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.BatterySettings", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("AgentID")
                        .HasColumnType("bigint");

                    b.Property<long>("BatteryID")
                        .HasColumnType("bigint");

                    b.Property<int>("Bay")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OemIdentifier")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("ServiceSettings", "GeniView.Data.Hardware.BatterySettings.ServiceSettings#BatteryServiceSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("ServiceCycleCount")
                                .HasColumnType("int");

                            b1.Property<int>("ServiceInterval")
                                .HasColumnType("int");
                        });

                    b.HasKey("ID");

                    b.HasIndex("AgentID");

                    b.HasIndex("BatteryID");

                    b.ToTable("BatterySettings");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.Device", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CommunityID")
                        .HasColumnType("bigint");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("CommunityID");

                    b.HasIndex("GroupID");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.DeviceSettings", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("AgentID")
                        .HasColumnType("bigint");

                    b.Property<bool?>("BargraphDimming")
                        .HasColumnType("bit");

                    b.Property<int>("Bays")
                        .HasColumnType("int");

                    b.Property<int?>("ChargingMode")
                        .HasColumnType("int");

                    b.Property<long>("DeviceID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeviceTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DischargingMode")
                        .HasColumnType("int");

                    b.Property<int>("LoggingInterval")
                        .HasColumnType("int");

                    b.Property<int>("OemIdentifier")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("AlertSettings", "GeniView.Data.Hardware.DeviceSettings.AlertSettings#DeviceAlertSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AlertType")
                                .HasColumnType("int");

                            b1.Property<int>("DisplayMode")
                                .HasColumnType("int");

                            b1.Property<int>("LowBatteryAlertInterval")
                                .HasColumnType("int");

                            b1.Property<int>("LowBatteryAlertLevel")
                                .HasColumnType("int");

                            b1.Property<int>("SystemMode")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("BatteryStateOfChargeSettings", "GeniView.Data.Hardware.DeviceSettings.BatteryStateOfChargeSettings#BatteryStateOfChargeSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("PercentageCutOff")
                                .HasColumnType("int");

                            b1.Property<double>("VoltageCutOff")
                                .HasColumnType("float");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PowerOutputSettings", "GeniView.Data.Hardware.DeviceSettings.PowerOutputSettings#DevicePowerOutputSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool?>("IsDCConverterFitted")
                                .HasColumnType("bit");

                            b1.Property<int>("PotValue")
                                .HasColumnType("int");

                            b1.Property<long>("Power")
                                .HasColumnType("bigint");

                            b1.Property<short>("Trim")
                                .HasColumnType("smallint");

                            b1.Property<double>("Voltage")
                                .HasColumnType("float");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("StandbySettings", "GeniView.Data.Hardware.DeviceSettings.StandbySettings#DeviceStandbySettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Current")
                                .HasColumnType("int");

                            b1.Property<bool?>("StandbyOnExternalPowerInput")
                                .HasColumnType("bit");

                            b1.Property<int>("Time")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SystemInformation", "GeniView.Data.Hardware.DeviceSettings.SystemInformation#DeviceSystemInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("SlaveSerialNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SystemPartNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SystemSerialNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UserInformation", "GeniView.Data.Hardware.DeviceSettings.UserInformation#DeviceUserInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("ID");

                    b.HasIndex("AgentID");

                    b.HasIndex("DeviceID");

                    b.ToTable("DeviceSettings");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.Event.DeviceEvent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("Agent_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Device_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("EventTypeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("Agent_ID");

                    b.HasIndex("Device_ID");

                    b.ToTable("DeviceEvents");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.InternalBatteryLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("Agent_ID")
                        .HasColumnType("bigint");

                    b.Property<double>("AverageCurrent")
                        .HasColumnType("float");

                    b.Property<int>("BatteryFirmwareVersion")
                        .HasColumnType("int");

                    b.Property<string>("BatterySerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BatterySerialNumberCode")
                        .HasColumnType("bigint");

                    b.Property<long?>("Battery_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("Bay")
                        .HasColumnType("int");

                    b.Property<double>("CalculatedCapacity")
                        .HasColumnType("float");

                    b.Property<double>("Current")
                        .HasColumnType("float");

                    b.Property<int>("CycleCount")
                        .HasColumnType("int");

                    b.Property<long>("DeviceLogIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventCode")
                        .HasColumnType("int");

                    b.Property<int>("EventCodeRaw")
                        .HasColumnType("int");

                    b.Property<string>("EventCodeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LogIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("OemIdentifier")
                        .HasColumnType("int");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RelativeStateOfCharge")
                        .HasColumnType("int");

                    b.Property<double>("RemainingCapacity")
                        .HasColumnType("float");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueLogIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Voltage")
                        .HasColumnType("float");

                    b.ComplexProperty<Dictionary<string, object>>("BatteryOperatingStatus", "GeniView.Data.Hardware.InternalBatteryLog.BatteryOperatingStatus#BatteryOperatingStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("StatusA")
                                .HasColumnType("int");

                            b1.Property<int?>("StatusARaw")
                                .HasColumnType("int");

                            b1.Property<string>("StatusAText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("StatusB")
                                .HasColumnType("int");

                            b1.Property<int?>("StatusBRaw")
                                .HasColumnType("int");

                            b1.Property<string>("StatusBText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("ID");

                    b.HasIndex("Agent_ID");

                    b.HasIndex(new[] { "Battery_ID", "Timestamp" }, "IX_BatteryID_Timestamp");

                    b.ToTable("InternalBatteryLog");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.InternalDeviceLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("Agent_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("BatteriesCharging")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesChargingCount")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesChargingRaw")
                        .HasColumnType("int");

                    b.Property<string>("BatteriesChargingText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteriesPoweringSystem")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesPoweringSystemCount")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesPoweringSystemRaw")
                        .HasColumnType("int");

                    b.Property<string>("BatteriesPoweringSystemText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteriesPresent")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesPresentCount")
                        .HasColumnType("int");

                    b.Property<int>("BatteriesPresentRaw")
                        .HasColumnType("int");

                    b.Property<string>("BatteriesPresentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Device_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("EventCode")
                        .HasColumnType("int");

                    b.Property<int>("EventCodeRaw")
                        .HasColumnType("int");

                    b.Property<string>("EventCodeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LogIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("PowerOutput", "GeniView.Data.Hardware.InternalDeviceLog.PowerOutput#DevicePower", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Current")
                                .HasColumnType("float");

                            b1.Property<double>("Voltage")
                                .HasColumnType("float");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "GeniView.Data.Hardware.InternalDeviceLog.Status#DeviceStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<int?>("StatusRaw")
                                .HasColumnType("int");

                            b1.Property<string>("StatusText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Temperature")
                                .HasColumnType("int");
                        });

                    b.HasKey("ID");

                    b.HasIndex("Agent_ID");

                    b.HasIndex(new[] { "Device_ID", "Timestamp" }, "IX_Device_ID_Timestamp");

                    b.ToTable("InternalDeviceLog");
                });

            modelBuilder.Entity("GeniView.Data.Web.Community", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<Guid>("CommunityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "GeniView.Data.Web.Community.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Fax")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetLineOne")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetLineTwo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Website")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("ID");

                    b.HasIndex("CommunityID")
                        .IsUnique();

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("GeniView.Data.Web.Group", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CommunityID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("GroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentGroupID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CommunityID");

                    b.HasIndex("GroupID")
                        .IsUnique();

                    b.HasIndex("ParentGroupID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.AgentBatteryLog", b =>
                {
                    b.HasOne("GeniView.Data.Agent.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("Agent_ID");

                    b.HasOne("GeniView.Data.Hardware.Battery", "Battery")
                        .WithMany("AgentBatteryLogCollection")
                        .HasForeignKey("Battery_ID");

                    b.Navigation("Agent");

                    b.Navigation("Battery");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.AgentDeviceLog", b =>
                {
                    b.HasOne("GeniView.Data.Agent.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("Agent_ID");

                    b.HasOne("GeniView.Data.Hardware.Device", "Device")
                        .WithMany("AgentDeviceLogCollection")
                        .HasForeignKey("Device_ID");

                    b.Navigation("Agent");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.Battery", b =>
                {
                    b.HasOne("GeniView.Data.Web.Community", "Community")
                        .WithMany("Batteries")
                        .HasForeignKey("CommunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeniView.Data.Web.Group", "Group")
                        .WithMany("Batteries")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.BatterySettings", b =>
                {
                    b.HasOne("GeniView.Data.Agent.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeniView.Data.Hardware.Battery", "Battery")
                        .WithMany("BatterySettingsCollection")
                        .HasForeignKey("BatteryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Battery");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.Device", b =>
                {
                    b.HasOne("GeniView.Data.Web.Community", "Community")
                        .WithMany("Devices")
                        .HasForeignKey("CommunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeniView.Data.Web.Group", "Group")
                        .WithMany("Devices")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.DeviceSettings", b =>
                {
                    b.HasOne("GeniView.Data.Agent.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeniView.Data.Hardware.Device", "Device")
                        .WithMany("DeviceSettingsCollection")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.Event.DeviceEvent", b =>
                {
                    b.HasOne("GeniView.Data.Agent.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("Agent_ID");

                    b.HasOne("GeniView.Data.Hardware.Device", "Device")
                        .WithMany("DeviceEventCollection")
                        .HasForeignKey("Device_ID");

                    b.Navigation("Agent");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.InternalBatteryLog", b =>
                {
                    b.HasOne("GeniView.Data.Agent.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("Agent_ID");

                    b.HasOne("GeniView.Data.Hardware.Battery", "Battery")
                        .WithMany("InternalBatteryLogCollection")
                        .HasForeignKey("Battery_ID");

                    b.Navigation("Agent");

                    b.Navigation("Battery");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.InternalDeviceLog", b =>
                {
                    b.HasOne("GeniView.Data.Agent.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("Agent_ID");

                    b.HasOne("GeniView.Data.Hardware.Device", "Device")
                        .WithMany("InternalDeviceLogCollection")
                        .HasForeignKey("Device_ID");

                    b.Navigation("Agent");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GeniView.Data.Web.Group", b =>
                {
                    b.HasOne("GeniView.Data.Web.Community", "Community")
                        .WithMany("Groups")
                        .HasForeignKey("CommunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeniView.Data.Web.Group", "ParentGroup")
                        .WithMany()
                        .HasForeignKey("ParentGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.Battery", b =>
                {
                    b.Navigation("AgentBatteryLogCollection");

                    b.Navigation("BatterySettingsCollection");

                    b.Navigation("InternalBatteryLogCollection");
                });

            modelBuilder.Entity("GeniView.Data.Hardware.Device", b =>
                {
                    b.Navigation("AgentDeviceLogCollection");

                    b.Navigation("DeviceEventCollection");

                    b.Navigation("DeviceSettingsCollection");

                    b.Navigation("InternalDeviceLogCollection");
                });

            modelBuilder.Entity("GeniView.Data.Web.Community", b =>
                {
                    b.Navigation("Batteries");

                    b.Navigation("Devices");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("GeniView.Data.Web.Group", b =>
                {
                    b.Navigation("Batteries");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
